### ISSUE TITLE
YAML instead of json/html for layouting 

### ISSUE THREAD

**Issue by Matt3o12** [gizak/termuid#1]
I believe YAML is a better choice to configure the layouts. 
Using JSON is just a pain (because its not really maintainable for humans -- it quickly gets messy and you're not able to comment the structure)
Html seems to be an overkill because the terminal will never be able to display such a complex layout.

**Comment by RangerMauve** [comment]
I'm not sure. XML still seems like it'd be more useful to most people since that's what a lot of UIs are made with today.

If we think about blessed, the library that inspired termui, there was a library based on it called [blessedoo](https://github.com/kevinhikaruevans/blessedoo) which used XML for the format, and it seems to work pretty well.

**Comment by Matt3o12** [comment]
Well you're probably right. I wasn't quite aware of the scope of the project. I first thought it was an extension so that you don't need to write layout code in go but it tours out to be false. 

Close #1
